### ISSUE TITLE
Uinput events

### ISSUE THREAD

**Issue by bhane** [Tangent128/lua-evdev#4]
I'm trying to get the fakemouse uinput example to work.

```lua
local e = require "evdev"
local fakeMouse = e.Uinput "/dev/uinput"
-- register supported events
fakeMouse:useEvent(e.EV_KEY)
fakeMouse:useEvent(e.EV_REL)
fakeMouse:useKey(e.BTN_0)
fakeMouse:useKey(e.BTN_1)
fakeMouse:useRelAxis(e.REL_X,-100,100)
fakeMouse:useRelAxis(e.REL_Y,-100,100)
fakeMouse:init()
-- inject a few events; mouse move, button press, button release
fakeMouse:write(e.EV_REL, e.REL_X, -50)
fakeMouse:write(e.EV_REL, e.REL_Y, 0)
fakeMouse:write(e.EV_SYN, e.SYN_REPORT, 0)
fakeMouse:write(e.EV_KEY, e.BTN_0, 1)
fakeMouse:write(e.EV_SYN, e.SYN_REPORT, 0)
fakeMouse:write(e.EV_KEY, e.BTN_0, 0)
fakeMouse:write(e.EV_SYN, e.SYN_REPORT, 0)
-- dispose
fakeMouse:close()
```
I can open the uinput device node, but writing the events doesn't seem to have any effect.

**Comment by Tangent128** [comment]
Run example/dump.lua on the corresponding /dev/input/event* node to see if the events are appearing? (add an io.read() right after :init() to pause it so the node's not destroyed before you can hook up the dump script)

Most likely, the device is created, but X.org is not set up to interpret it as an input device. I put the following in xorg.conf.d:

```
Section "InputClass"
	Identifier "fakemouse"
	MatchDevicePath "/dev/input/event*"
	MatchProduct "Lua Mouse"
	Driver "evdev"
	
	Option "StartMouseEnabled" "True"
	
EndSection
```

And then pass "Lua Mouse" as the parameter to :init().

**Comment by bhane** [comment]
Adding the above to xorg.conf.d worked!
However, I couldn't extend it to work with a virtual keyboard.
in xorg.conf.d:
```
Section "InputClass"
    Identifier "fakekeyboard"
    MatchDevicePath "/dev/input/event*"
    MatchProduct "Lua Keyboard"
    Driver "evdev"
    Option "StartKeysEnabled" "True"
EndSection
```
(I also tried with MatchIsKeyboard "on")

and running:
```
local e = require "evdev"
local fakeKeyboard = e.Uinput "/dev/uinput"
fakeKeyboard:useEvent(e.EV_KEY)
fakeKeyboard:useKey(e.KEY_A)
fakeKeyboard:init("Lua Keyboard")
fakeKeyboard:write(e.EV_KEY, e.KEY_A, 1) 
fakeKeyboard:close()
```
The device also opens, but I can't get the key events to register.

**Comment by Tangent128** [comment]
Try adding this after you write() the keydown event:

    fakeKeyboard:write(e.EV_SYN, e.SYN_REPORT, 0)

The Linux evdev system uses SYN events to separate groups of simultaneous events, so uinput waits for a SYN event before it sends a "batch" of events.

See in the fakemouse example how SYN events are used to group the two REL events together, then send the button click and release as separate events.

**Comment by bhane** [comment]
Excellent! Thanks for the help.
