### ISSUE TITLE
Order of operations

### ISSUE THREAD

**Issue by daurnimator** [Tangent128/lua-evdev#5]
Reading through the code, I noticed that resources can be leaked.
e.g. https://github.com/Tangent128/lua-evdev/blob/master/evdev/core.c#L79 could throw due to low memory, and the fd would be lost.

Instead:
  - allocate the userdata upfront
  - initialise the members to safe 'invalid' values (that your `__gc` won't act on, e.g. -1 for an fd field)
  - attach the metatable
  - finally: `open` and get an fd.

Also needs to be fixed down in `uinput_open`

**Comment by Tangent128** [comment]
Does `malloc` ever actually fail on Linux?

But good catch, and an easy fix; I'll get on it soon.

**Comment by daurnimator** [comment]
> Does malloc ever actually fail on Linux?

Yes. e.g.
  - If you're out of virtual address space
  - if you have overcommit set to off
  - if you've been limited via `setrlimit`

More specific to lua:
  - if you're using a custom lua allocator
  - in luajit, if you go above the 1GB limit

**Comment by Tangent128** [comment]
Fixed, tagged as version 2.2, and published to LuaRocks.

**Comment by daurnimator** [comment]
Fix in 4e6ab339683e61060a22939c02e413c2e012acd7 looks good :)
