### ISSUE TITLE
Undefined symbol: luaL_setfuncs

### ISSUE THREAD

**Issue by rkelly** [Tangent128/lua-evdev#6]
Thanks for this library.

I'm trying to get a [Griffin PowerMate](https://support.griffintechnology.com/product/powermate/) to work for my son in Lua and Love2d so he can use it for making games.

I'm testing on Linux with Love 0.9.2-1. The system has lua 5.1, 5.2, and 5.3 installed.

I'm able to read the controller using this library. But when I try adding the `evdev` module to a Love2d program, I get the error:

```
error loading module 'evdev' from file '/usr/local/lib/lua/5.1/evdev.so': /usr/local/lib/lua/5.1/evdev.so: undefined symbol: luaL_setfuncs.
```

I saw the [earlier post on this subject](https://github.com/Tangent128/lua-evdev/issues/3). So I cloned from your master and used `make` to compile a new evdev.so. But I continue to get the same error.

Any ideas? Does `make` have to be called a certain way to build a 5.1-friendly version? Thanks.

**Comment by Tangent128** [comment]
Responding to this via offline email, so I can't refer to your links at the
moment; forgive any repetition.

But my initial guess would be that your system version of Lua is 5.2 or
5.3, while Love2d is based on Lua 5.1; do you know offhand which Lua
version's headers you are building against?

**Comment by Tangent128** [comment]
OK, looking at this properly now; I see you edited in some more information.

Probably the compiler is picking up the 5.2 or 5.3 version of Lua then, yeah.

If you set the CPATH environment variable before compiling, you can tell the compiler what directories to search for files in; find which folder has the right versions of `lua.h` and `lauxlib.h` and set CPATH to that.

For example, `export CPATH=/usr/include/lua5.1/` on ArchLinux.

**Comment by rkelly** [comment]
You were right. The compiler must have been using Lua 5.2 or 5.3.

The CPATH trick didn't solve the problem for me. But then I uninstalled Lua 5.2 and 5.3, and recompiled, and that version worked.

We have our PowerMate working in Love2d. Thanks!

**Comment by Tangent128** [comment]
Glad to hear you found a solution, hope you have fun!

Hardware's always a great way to foster interest in programming.

(I'll probably double-check how to pick the version anyways, out of curiousity.)
